### ISSUE TITLE
Rolle Analyst ergänzen P2

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#11]

**Comment by edgar-butwilowski-win** [comment]
Braucht es tatsächlich eine separate Rolle "Analyst", oder kann diese identisch sein mit dem "Administrator"? Es ist zu bedenken, dass es ideal ist, wenn es jederzeit mehr als nur einen Administrator gibt (als Ausfall-Absicherung). Falls es die Rolle braucht, was sind die Rechte-/Funktionen-Unterschiede zum Administrator?

**Comment by morasax** [comment]
Die Rolle "Analyst" braucht im Gegensatz zum Admin keine Vollrechte auf alles (Anpassen von Rollen, usw.). Wichtig ist, dass der Analyst Zugang zu allen Analysemöglichkeiten hat und auf der DB direkt Informationen abziehen kann. Hier wäre ich dankbar, wenn wir zu gegebener Zeit genau definieren könnten, wo welche Informationen zur Verfügung stehen. Ich mache mir im Dokument einen entsprechenden Hinweis. Issue bitte offen lassen.

**Comment by morasax** [comment]
Soweit mir bekannt ist, wurde diese Rolle umgesetzt. Inhaber sind Stefan Gahler und Monica Ramsperger Saxer. Deshalb schliesse ich das Ticket.
