### ISSUE TITLE
Rolle Projektleiter ergänzen P3

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#12]

**Comment by edgar-butwilowski-win** [comment]
Braucht es tatsächlich eine separate Rolle "Projektleiter" tatsächlich? Falls es die Rolle braucht, was sind die Rechte-/Funktionen-Unterschiede zu anderen bereits bestehenden Rollen?

**Comment by morasax** [comment]
Nein, es braucht keine Rolle Projektleiter. Es bedarf nur der Rollen gem. Rollen Pt. 4.6 im Dokument (aktuell Admin, Besteller, Gebietsmanager, Eventmanager, Ev. Verkehrsmanager (ist noch in Abklärung, wait) und Analyst

**Comment by morasax** [comment]
Ich schliesse das Ticket. Die Rolle PL ist generell vorhanden. Diese benötigen wir, um einzelne Phasen prozessgesteuert via Rollenwechsel voranzutreiben. Hierzu werde ich ein separates Ticket erfassen.
