### ISSUE TITLE
Slider für Zeiträume soll tatsächliche Tertial-Angabe anzeigen, auch wenn diese unter dem zulässigen Minimalwert des Sliders liegt

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#122]

**Comment by morasax** [comment]
Ich verstehe leider nicht, was du damit meinst. Kannst du mir bitte weiterhelfen?
Wir benötigen Quartale, nicht Tertiale - dies wurde umgesetzt und ist ok (#243).
