### ISSUE TITLE
Baustellengeometrie soll in der Vorschaukarte sichtbar sein P2

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#13]
Die Geometrie einer Baustelle (Bedürfnis/Massnahme) soll bereits in der Vorschaukarte (auf den Material Cards) sichtbar sein

**Comment by edgar-butwilowski-win** [comment]
Dies ist eine recht umfangreiche Änderung, daher für später zurückgestellt.

**Comment by morasax** [comment]
Aus meiner Sicht gehört dies zum #6 (generelle Thematik zur Darstellung der "Einstiegsseite" bei Bedarf und Baumassnahme. Bitte an Sitzung gemeinsam besprechen.

**Comment by morasax** [comment]
Prio 2	 --> muss mit GoLive vorhanden sein
Ich gehe davon aus, dass es sich bei diesem Ticket um die Ansicht in der "Willkommen"Seite handelt. Dort benötigen wir einerseits eine Auflistung aller vorhandenen Infos (Bedarfe und Bauvorhaben, bei welchen man in irgend einer Form beteiligt ist) und andererseits eine grafische Übersicht aller Bedarfe und Bauvorhaben (alle) mit entsprechenden Infos mit MouseOver, Farben, usw. Dies hatten wir bereits mehrfach besprochen. Ich bin gerade unsicher, ob wir nicht ein aktuelleres Ticket zu diesem Thema haben. Du?

**Comment by morasax** [comment]
Ich schliesse das Ticket. Dieses wurde zwischenzeitlich neu erfasst in mehreren Schritte. Die Thematik wurde bereits mehrfach aufgenommen. Es handelt sich um die Tickets #311 / #378 usw.
