### ISSUE TITLE
In Bauvorhaben-Karte: Geodaten Polygone Einfärbung anpassen (nur Polygon-Rand) P1

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#135]
- Bedarf nicht zugeordnet: R47,G85,B151
- Bedarf zugeordnet: R143,G170,B220

**Comment by morasax** [comment]
Prio 1 	--> muss vor Testing vorhanden sein
Informationen per 30.04.2024 erneut an Sitzung besprochen da bis dahin Farben unklar waren. 
Bitte umsetzen gem. Infos in pptx bzw. Excel (Sharepoint).
Beinhaltet nur Bedarf und Bauvorhaben gem. pptx. Für restliche Flächen eröffne ich ein neues Ticket

[WiKIS - Zusatzinfos zu Issues.pptx](https://github.com/user-attachments/files/16588528/WiKIS.-.Zusatzinfos.zu.Issues.pptx)
