### ISSUE TITLE
Status "in Prüfung" ergänzen PI

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#14]
Der Status "in Prüfung" wird automatisch gesetzt, sobald zu einem Bedarf eine Massnahme erzeugt wurde. Dann erhält sowohl der zugehörige Bedarf als auch die Massnahme den Status "in Prüfung". Der aktuell bestehende Status "in Bearbeitung" wird dafür entfernt.

**Comment by morasax** [comment]
Die Stati sind aktuell bei mir in Bearbeitung und hängen mit den Prozessen sowie dem Koordinationsreglement zusammen. Wir müssen an der nächsten Sitzung miteinander absprechen, welche Stati bereits gesetzt werden können. Die Prozesse sowie das Reglement sind zur Zeit noch in Bearbeitung.

**Comment by morasax** [comment]
Ich erlaube mir das Ticket abzuschliessen.
