### ISSUE TITLE
Status "verifiziert" ergänzen

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#15]
Der Status "verifiziert" kann an einer Massnahme manuell gesetzt werden. Dann erhalten sowohl alle zugehörigen Bedarfe als auch die Massnahme den Status "verifiziert".

**Comment by morasax** [comment]
Ich gehe davon aus, dass dies bereits korrekt umgesetzt ist und schliesse das Ticket
