### ISSUE TITLE
Status "Vorstudie" ergänzen P2

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#16]

**Comment by morasax** [comment]
Prio 2	 --> muss mit GoLive vorhanden sein
Hängt zusammen mit: 
Bauvorhaben - Register Termine VS P2 #287
Register Termine - Vorstudie anpassen P2 #282
--> in WiKIS muss unter den Bauvorhaben nach dem Status "Vorstudie" gesucht werden können (Filter)

**Comment by morasax** [comment]
Filter für VS ist vorhanden -  Ticket closed
