### ISSUE TITLE
Status "genehmigt" ergänzen

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#17]
Der Status "genehmigt" kann an einer Massnahme manuell gesetzt werden. Dann erhalten sowohl alle zugehörigen Bedarfe als auch die Massnahme den Status "genehmigt". Die Status "prov. festgesetzt", "def. festgesetzt" und "ausgeführt" werden dafür entfernt.

**Comment by morasax** [comment]
Ich gehe davon aus, dass dieses Ticket bereits seit geraumer Zeit umgesetzt ist und schliesse es ab.
