### ISSUE TITLE
Status "neu" ergänzen

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#18]
Der Status "neu" wird automatisch am Baubedürfnis gesetzt, sobald dieses erzeugt wurde.

**Comment by edgar-butwilowski-win** [comment]
Aktuell heisst dieser Status "nicht koordiniert". Ich finde "nicht koordiniert" sprechender als "neu". Soll diese Änderung tatsächlich durchgeführt werden?

**Comment by morasax** [comment]
Ja.  Grundsätzlich sind alle koordiniert, deshalb stimmt "nicht koordiniert" nicht.
Bitte alle Stati noch "wait" -> wir müssen das an der Sitzung besprechen. #14,#15, #16,#17, #18

**Comment by morasax** [comment]
Die Stati ergeben sich aus dem Excel im Sharepoint. Ich gehe davon aus, dass dieses Ticket obsolet ist bzw. bereits umgesetzt und schliesse dieses ab.
