### ISSUE TITLE
Auf der Seiten "Bedarfsklärung" und "Stellungnahme" den Button "Abschliessen" ergänzen

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#186]
- Nur Gebietsmanager und Admin können diesen sehen
- Bedarfsklärung wechselt in Status "verifiziert"
- Stellungnahme wechselt in Status "koordiniert
- Datum des Abschlusses wird gespeichert
- Nach Klick verschwindet der Button
- Anschliessend ist keine Eingabe zur Bedarfsklärung mehr möglich

**Comment by morasax** [comment]
Der neue Button «Wiedereröffnen» (aus Nr. 187) ist offenbar direkt neben dem Button Abschliessen platziert. Er ist allerdings nur für den Admin sichtbar und nur im richtigen Status des Bauvorhabens --> was heisst das? Ich sehe keinen entsprechenden Button. Auch die Daten unter "Historie" sehe ich nicht.
