### ISSUE TITLE
Auf der Seite der Bedarfsklärung einen Button "Wiedereröffnen" ergänzen

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#187]
- Nur der Admin kann diesen sehen
- Wird nur eingeblendet, wenn das Bauvorhaben vorgängig vom Gebietsmanager abgeschlossen wurde

**Comment by morasax** [comment]
Nach Login als GM (Tobias Juon) sehe ich bei "Bedarfsklärung" sowie "Stellungnahme", dass er diese abgeschlossen hat (Button ABGESCHLOSSEN). Ich sehe jedoch keinen Button zur Wiedereröffnung
