### ISSUE TITLE
Baumassnahmen um Attribut "Werk" ergänzen

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#19]
Das Attribut "Werk" beinhaltet zu welchem Werk die Baumassnahme gehört. Mögliche Werte sind: Wasser, Abwasser, Strom, Strasse.

**Comment by edgar-butwilowski-win** [comment]
Wie ist es bei Baumassnahmen, die aus einer Koordination mehrerer Baubedürfnisse (die aus unterschiedlichen Werken kamen) entstanden sind? Welchem Werk sind diese zuzuordnen?

**Comment by morasax** [comment]
Dieses Ticket wird geschlossen, es ist bereits umgesetzt
