### ISSUE TITLE
Es soll eine neue Rolle "Vernehmlasser" eingerichtet werden P3

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#191]
- Diese Rolle kann nur die Übersicht der Bauvorhaben sehen und nur Bauvorhaben öffnen

**Comment by morasax** [comment]
Prio 2	 --> muss mit GoLive vorhanden sein
Die Rolle heisst "Vernehmlassende". Diese Rolle ist im Excel auf Sharepoint hinterlegt. Info: Haben keinen Zugriff auf das Tool, lediglich im Rahmen von Vernehmlassungen (elektr. Zirkulation) für die Eingabe von Rückmeldungen.
