### ISSUE TITLE
Ein neues Baubedürfnis ist zunächst nur für den Bedarfssteller sichtbar

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#21]
Es wird ein Button "Publizieren" auf dem Bedürfnisformular ergänzt, über den das Bedürfnis für alle sichtbar gemacht werden kann. Das noch nicht publizierte Baubedürfnis kann der Bedarfssteller löschen (neuer Button "Löschen"). Sobald das Bedürfnis publiziert ist, kann es nicht mehr bearbeitet werden.

**Comment by morasax** [comment]
Ist bereits umgesetzt und wird deshalb geschlossen
