### ISSUE TITLE
Bedarf kann als Entwurf und definitiv gespeichert werden, ohne dass ein Datum eingegeben werden muss P1

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#231]

**Comment by edgar-butwilowski-win** [comment]
Ich gehe hierbei davon aus, dass es sich um das Umsetzungsjahr einer übergeordneten Massnahme handelt. Bei einer nicht-übergeordneten Massnahme sind die Realisierungszeiträume immer gesetzt.

**Comment by morasax** [comment]
Beim Erfassen eines Bedarfs hat man die Möglichkeit, via Schieberegler 3 Termine zu setzen, oder Übergenordnete Massnahme anzuwählen.
Schieberegler muss nicht betätigt werden, man kann auch speichern ohne eine Angabe - dies ist nicht korrekt, es muss eine Angabe gemacht werden (Muss-Feld: entweder Schieberegler oder Übergeordnete Massnahme).
Wir die Übergeordnete Massnahme gewählt, kann nicht gespeichert werden, ohne Datumsangabe, dies ist korrekt.

**Comment by morasax** [comment]
Es ist aus Sicht GM dringend notwendig, dass ein aktuelles Datum angegeben wird - Schieberegler oder Übergeordnete Massnahme bzw. deren Termine müssen eingegeben werden. Es darf nicht sein, dass die Schieberegler nicht angepasst werden - Speichern ohne mind. eines Parameters der Zeitangaben sind nicht zulässig.
Klären: Wie kann sichergestellt werden, dass es den Bedarfsstellern bewusst wird? Darstellung der Zahlen erst in Rot, und nach effektivem Verschieben in Schwarz? Oder erst gar nicht sichtbar, erst mit Schieben?

**Comment by edgar-butwilowski-win** [comment]
Wie wäre hier vorzugehen? Sollen die Zahlen in rot dargestellt werden? Jedoch, grundsätzlich könnte es ja schon vorkommen, dass gerade bei Bedarfen zur kurzfristigen Umsetzung der früheste, Wunsch- und späteste Termin alle gleich im ersten nächsten Quartal liegen. In dem Fall müsste keiner der Schieberegler geschoben werden und die Termine wären trotzdem richtig eingegeben.

**Comment by morasax** [comment]
Nein, es gibt keine "kurzfristigen Bedarfe" in WiKIS. Mit WiKIS sollen alle Bedarfe langfristig geplant werden können, deshalb ist eine frühe Aufnahme wichtig. Bitt einfach eine Bemerkung, dass nicht gespeichert werden kann, wenn die Termine nicht bearbeitet wurden.

**Comment by edgar-butwilowski-win** [comment]
Es soll eine Meldung (Dialogfenster) kommen, wenn der Benutzer den Regler "Wunschtermin" kein einziges Mal verschoben hat.

**Comment by edgar-butwilowski-win** [comment]
Ist erledigt, muss noch ausgerollt werden.
