### ISSUE TITLE
Bauvorhaben bzw. Beteiligte kann nicht durch GM editiert werden, keine Berechtigung

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#232]
Beispiel-Bauvorhaben: Anton-Graff-Strasse

**Comment by morasax** [comment]
NOK – mit Login GM können Beteiligte hinzugefügt werden (OK) aber keine bereits vorhandenen Beteiligten weggenommen werden - das Häklein kommt nach Verlassen der Seite wieder (Bsp. AfS, bei Bauvorhaben / Massnahme 2). Zudem: Es erscheint eine Fehlermeldung

**Comment by edgar-butwilowski-win** [comment]
@morasax Danke für den Hinweis. Kann den Bug nun nachvollziehen. Nehme das Ticket auf die Liste.
