### ISSUE TITLE
Das Fälligkeitsdatum von Bauvorhaben soll automatisch berechnet werden

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#239]

**Comment by morasax** [comment]
Welches Fälligkeitsdatum meinst du genau?
Die Fälligkeit der elektronischen Zirkulationen (erst Bedarfsklärung, dann Stellungnahme, ...) soll sich errechnen, sobald die elektronische Zirkulation ausgelöst wird. Dann soll der Chip grün, orange oder rot werden (gem. Definition im Foliensatz). Dies kann ich nicht testen, da ich die Daten nicht ändern kann und die Vernehmlassung nicht steuern kann (kein Formular, kein Tab).
Sobald der Bedarf durch den GM übernommen wurde, soll anhand der Dauern (gem. Auszug Excel SKS) errechnet werden, auf welche Sitzung SKS dieses Vorhaben frühestens möglich ist und dort den Termin setzen.
