### ISSUE TITLE
Die Liste der Beteiligten bei den Bauvorhaben aktualisiert nicht immer

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#245]

**Comment by morasax** [comment]
Siehe Slides gem. Mail - hier hat es offenbar noch einen Fehler. Bereits gesetzte Beteiligte lassen sich nicht wieder entfernen und bleiben daher auch in der Übersicht bestehen. Neue hinzufügen funktioniert.
