### ISSUE TITLE
Die Spalte "Status" in der Tabelle der Bedarfsübersicht soll weiter nach rechts geschoben werden

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#247]
- Die Spalte "Wunschtermin" kann entfernt werden
- Spalte "Bezeichnung" => "Titel/Strasse"
- Spalte "Gebietsmanagement" => "GM"

**Comment by morasax** [comment]
Gem. Slides (Präsentation) fehlen noch einzelne Punkte in Bezug auf Bedarfe.
Die gleichen Task müssen bei der Übersicht in Willkommen und bei Bauvorhaben umgesetzt werden, dies ist noch komplett offen.
