### ISSUE TITLE
Die Baumassnahme wird um einen Reiter "Vernehmlassung" erweitert

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#25]
Im Bereich "Vernehmlassung" können die Besteller je nach Massnahmen-Status eine Rückmeldung zur Bedarfsklärung oder eine Stellungnahme abgeben. Der Gebietsmanager kann die Prozessschritte aktivieren und er kann einen Infoversand auslösen. Die Besteller geben ihre Rückmeldungen in einem Freitext-Feld ein. Sie können über eine Checkbox auch "Kein Bedarf" bzw. "Keine aktive Rückmeldung" melden. Diese Rückmeldung werden in die Historie der Baumassnahme aufgenommen (wer, wann).

**Comment by edgar-butwilowski-win** [comment]
Erste Preview-Funktionen dieses Tickets sind umgesetzt in V2023.11.13.

**Comment by morasax** [comment]
Aus meiner Sicht bereits umgesetzt und/oder in einem neueren Ticket erfasst. Ich schliesse das Ticket
