### ISSUE TITLE
Phasen/Status mit entsprechenden Farben darstellen (Prio 2)

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#253]
Gem. Mail vom April 2024
Bitte Phase/Status in den entsprechenden Farben darstellen

**Comment by morasax** [comment]
Siehe Excel "WiKIS_Rollen_Funktionsmatrix" - darin sind im Register "Farben" alle benötigen Infos vorhanden.

**Comment by edgar-butwilowski-win** [comment]
Phasenfarben in den "Chips" korrigiert. Der Status-Chip wird nun auch in der Tabellenansicht der Bauvorhaben angezeigt.

**Comment by edgar-butwilowski-win** [comment]
Hallo Monica

Das Schliessen des Tickets bezieht sich auf die neueste Dev-Version, die noch nicht in der Produktivumgebung ausgespielt ist. Daher ist die Anpassung für dich noch nicht sichtbar.

Vielleicht können wir es ja generell so machen, dass nicht ich die Tickets abschliesse, sondern nur du. Ich würde erledigte Tickets dann nur noch auf «In review» setzen:

***@***.***

Und du würdest dann nach der Prüfung das Ticket schliessen:

***@***.***

Wollen wir das so handhaben?

Gruss
Edgar


Von: morasax ***@***.***>
Gesendet: Dienstag, 27. August 2024 10:38
An: Geoinformation-Winterthur/roadwork-portal-client ***@***.***>
Cc: Butwilowski Edgar ***@***.***>; State change ***@***.***>
Betreff: Re: [Geoinformation-Winterthur/roadwork-portal-client] Phasen/Status mit entsprechenden Farben darstellen (Prio 2) (Issue #253)


Reopened #253<https://github.com/Geoinformation-Winterthur/roadwork-portal-client/issues/253>.

**Comment by morasax** [comment]
Bin mir unsicher ob wir ein Missverständnis haben - es gibt keinen "Status-Chip" (was/wo wäre dieser?).
Es gibt Bauvorhaben -> Stammdaten -> Übersicht bei den Vernehmlassungen einen "Fälligkeits-Chip". Dieser wechselt die Farben (grün/gelb/rot). Dieser Chip muss auch auf der Übersicht im Willkommen sein. Dort müsste noch ein Ticket vorhanden sein #274 
PS: Ja, das passt. Wenn ich nach Prüfung sehe das alles passt, werde ich künftig die Tickets schliessen.
