### ISSUE TITLE
Überall bei den Bewertungen die Farben der Buttons auf grau setzen

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#256]

**Comment by morasax** [comment]
Bitte bei Bauvorhaben die Bewertungen ebenfalls auf Grau setzen.

**Comment by morasax** [comment]
Soweit ich sehen kann, wurde dieser Punkt umgesetzt - Ticket wird geschlossen
