### ISSUE TITLE
Umbenennen von "Baubedarf" und "Baumassnahme"

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#27]
Bitte folgende Umbenennungen (Auf Navigation und generell) vornehmen:
Aus "Baubedürfnisse" wird neu "Baubedarf"
Aus "Baumassnahme" wird neu "Bauvorhaben"
Zeitrahmen: Prio. 1 d.h. vor Testing durch Dritte

**Comment by edgar-butwilowski-win** [comment]
Lösung ist in V2023.11.13 eingebaut.
