### ISSUE TITLE
Usertest - Kostenschätzung anpassen P3

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#271]
Prio 3	 --> erfolgt nach GoLive. Wird gesammelt und periodisch in die aktive Umgebung aufgenommen.

Bauvorhaben, Register  "Übersicht" -> Kostenschätzung (CHF) anpassen.

- Feld erscheint nur, wenn MA = TBA. Dann muss das Feld allerdings zwingend ausgefüllt werden (Muss-Feld)
- Eingabefeld "Kostenschätzung" nicht vorhanden. Erscheint erst nach Klick auf "SPEICHERN" - dies muss zu Beginn ersichtlich sein (möglich?)
- Optimal wäre es, wenn die Zahlenwerte nach dem speichern finanztechnisch angezeigt werden (1000er Trennung, sodass besser lesbar)
- Pfeile rechts bitte entfernen, da wir mit grossen Zahlen arbeiten, machen 1er Schritte keinen Sinn.

**Comment by morasax** [comment]
Register "Kosten" darf für alle ersichtlich sein

**Comment by edgar-butwilowski-win** [comment]
Ist hier "MA = TBA" nicht immer gegeben? Bauvorhaben können nur durch GM oder Admin editiert werden, diese sind doch immer MA von TBA.

**Comment by edgar-butwilowski-win** [comment]
Wie wäre es hierbei, die **Pfeile rechts** beizubehalten, jedoch statt 1er-schritte z.B. 100er- oder 1000er-Schritte zu verwenden?

**Comment by edgar-butwilowski-win** [comment]
Finanztechnische Anzeige war bereits eingebaut
