### ISSUE TITLE
Übersicht Willkommen erstellen P2

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#274]
Prio 2	 --> muss mit GoLive vorhanden sein

Willkommen
Bitte Text mit Gross-/Kleinschreibung, nicht wie jetzt alles gross und Texte generell anpassen
Bitte wie im PowerPoint notiert umsetzen.

[WiKIS - Zusatzinfos zu Issues - Willkommen .pptx](https://github.com/user-attachments/files/16759423/WiKIS.-.Zusatzinfos.zu.Issues.-.Willkommen.pptx)

**Comment by morasax** [comment]
Bitte neben dem Einfügen der Informationen gemäss pptx (Ansichten/Übersicht indiv. Startseite) zusätzlich folgendes korrigieren: 
**(der Abteilung Planung & Koordination bitte löschen)**
Danach lautet der Text nur noch: Willkommen "Name/Vorname gem. Logi" im WiKIS (Winterthurer Koordinationstool für Infrastrukturvorhaben im öffentlichen Strassenraum) des Tiefbauamts Winterthur.

**Comment by edgar-butwilowski-win** [comment]
"der Abteilung Planung & Koordination" => "des Tiefbauamts"

**Comment by morasax** [comment]
Danke für das Anpassen des Textes.
Das Ticket umfasst jedoch nicht nur den Text, sondern vor allem die Anpassung der Willkommen-Seite.
Es ist schwierig für mich, alle einzelnen Punkte aufzunotieren, diese sind im pptx. ersichtlich
Es muss jedoch:
Der Text "Es sind zurzeit keine Bauvorhaben in der Vernehmlassung" gelöscht werden"
neuer Text hinzufügen:  Folgende Einträge stehen im Zusammenhang mit deinem persönlichen Login:
Darunter muss eine Auflistung erscheinen mit Bezeichnung/GM/PL/Lead/Beteiligte/Status/Phase/Wunschtermin/Fälligkeit

**Comment by edgar-butwilowski-win** [comment]
Die Vorgaben im PowerPoint lassen sich so nicht 1:1 umsetzen. Nach Wunsch soll es eine Liste sowohl für Bedarfe als auch für Bauvorhaben sein. Jedoch enthält die Tabelle einige Attribute, die es nur bei Bauvorhaben gibt: Projektleiter, Lead, Beteiligte, Fälligkeit. Es gibt nun Alternativen zur Lösung, aus denen zu wählen ist:
- Die Spalten der fraglichen Attribute werden aus der Tabelle entfernt
- Die Spaltenwerte bleiben für Bedarfe leer
- Die Spalten werden für Bedarfe nach "best effort" befüllt, d.h. es werden die Werte anderer Attribute der Bedarfe eingesetzt, die den jeweiligen Attributbezeichnungen der Bauvorhaben ähnlich sind
- Auf der Seite werden zwei Tabellen vorgehalten, eine für Bedarfe, eine für Bauvorhaben, jeweils mit unterschiedlichen Spalten
Welcher Lösungsweg ist gewünscht?

**Comment by edgar-butwilowski-win** [comment]
Es wurde bestimmt, dass zwei Tabellen (Bedarf und Bauvorhaben) vorgehalten werden sollen. Anzuzeigende Attribute für Bedarfe-Tabelle werden noch genannt.

**Comment by morasax** [comment]
[WiKIS - Zusatzinfos zu Issues - Willkommen.pptx](https://github.com/user-attachments/files/17519582/WiKIS.-.Zusatzinfos.zu.Issues.-.Willkommen.pptx)

**Comment by morasax** [comment]
-> siehe Ticket #275 - dieses Ticket wird geschlossen

**Comment by morasax** [comment]
Das Ticket 275 habe ich geschlossen. Es handelt sich Themenmässig um das gleiche. Dort waren jedoch Korrekturmassnahmen sowie Seitenaufbau beinhaltet. Im aktuellen Ticket geht es nur noch um den Seitenaufbau.
Wir benötigen im "Willkommen" eine Spalte für Bedarfe, eine für Bauvorhaben sowie ein Bild oder einen Link auf das WinWebGIS. Dort muss eine Gesamtsicht aller Vorhaben möglich sein, inkl. Tooltip

**Comment by morasax** [comment]
Ich habe gesehen, dass du in der aktuellen Version unter "Willkommen" bei den Bedarfen den Auslösegrund dazugefügt hast. Sieht gut aus, bitte belassen, wenn auch nicht von mir so definiert.
Ich habe das pptx. entsprechend angepasst. Bitte dieses verwenden, auch die Reihenfolge stimmt hier.

[WiKIS - Zusatzinfos zu Issues - Willkommen.pptx](https://github.com/user-attachments/files/17544768/WiKIS.-.Zusatzinfos.zu.Issues.-.Willkommen.pptx)

**Comment by edgar-butwilowski-win** [comment]
In V2024.30 erledigt

**Comment by edgar-butwilowski-win** [comment]
Und Link auf WinWebGIS-Applikation ganz unten ergänzen

**Comment by edgar-butwilowski-win** [comment]
Link auf WinWebGIS ist ergänzt

**Comment by morasax** [comment]
Lieber Edgar

Leider sehe ich nichts. Ich habe mehrere Male aktualisiert und mich mit verschiedenen Rollen eingeloggt, aber einen Link auf das WinWebGIS kann ich leider nicht sehen.
LG
Monica

***@***.***

Von: Edgar Butwilowski ***@***.***>
Gesendet: Montag, 9. Dezember 2024 17:37
An: Geoinformation-Winterthur/roadwork-portal-client ***@***.***>
Cc: Ramsperger Saxer Monica ***@***.***>; State change ***@***.***>
Betreff: Re: [Geoinformation-Winterthur/roadwork-portal-client] Übersicht Willkommen erstellen P2 (Issue #274)


Link auf WinWebGIS ist ergänzt

**Comment by edgar-butwilowski-win** [comment]
WinWebGIS-Button und folgenden Text auf der Willkommensseite nach oben:
"Über das WinWebGIS findest du die graphisch Darstellung der Bauvorhaben.
Für Details bitte diesen Button klicken:"

**Comment by edgar-butwilowski-win** [comment]
Der WinWebGIS-Button wurde in V 2024.32 auf der Willkommensseite nach oben verlagert.
