### ISSUE TITLE
Benutzer soll mehrere Rollen zugleich innehaben können

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#280]
- Die Rolle muss vom Benutzer noch vor dem Login ausgewählt werden
- Wählt der Benutzer eine Rolle, die er nicht hat, scheitert der Login
- Die Benutzerkonfiguration ist anzupassen: Rolle neu als Checkbox

**Comment by morasax** [comment]
Die Auswahl der Rollen erscheint aktuell immer, unabhängig davon, ob die Person eine oder mehrere Rollen hat. Besteht die Möglichkeit es so zu konfigurieren, dass bei einer Rolle diese automatisch hinterlegt ist (keine Auswahl), und bei mehreren Rollen eine Auswahl erscheint?
