### ISSUE TITLE
Register Termine - Vorstudie anpassen P2

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#282]
Prio 2	 --> muss mit GoLive vorhanden sein

Bauvorhaben -> Register Termine -> Vorstudie

Bitte neue Felder hinzufügen
Vorstudie vorgesehen -> Häklein (bereits vorhanden, ok)
Projektauftrag VS genehmigt -> Neues Feld -> Datumsfeld, manueller Eintrag (dieses Startet gleichzeitig die Phase 2, Bearbeitungslead neu bei AMO)
Vorstudie genehmigt -> Neues Feld -> Datumsfeld, manueller Eintrag (dieses Beendet gleichzeitig die Phase 2)

Wenn das Häklein bei Vorstudie gesetzt wird (Register Termine), dann muss auch das planerische Start- und Enddatum eingegeben werden (Feld: Vorstudie Start), ansonsten darf nicht weitergefahren/gespeichert werden (muss Feld, wenn Vorstudie).
Vorstudie genehmigt: Erst wenn dieses Datum gesetzt ist, darf der Prozess weitergehen.

[WiKIS - Zusatzinfos zu Issues.pptx](https://github.com/user-attachments/files/16348127/WiKIS.-.Zusatzinfos.zu.Issues.pptx)

**Comment by morasax** [comment]
Die Reihenfolge der Felder ist nicht korrekt. Zusammen gehören die Felder Plantermin Vorstudie Start und Plantermin Vorstudie Ende sowie die beiden Felder Projektauftrag Vorstudie genehmigt und Vorstudie genehmigt

**Comment by edgar-butwilowski-win** [comment]
Reihenfolge der Felder ist nun korrigiert.

**Comment by morasax** [comment]
Ich sehe noch immer die falsche Reihenfolge. Habe heute 3 Bedarfe angelegt, bei allen ist die Reihenfolge wie folgt: 
Plantermin: Vorstudie Start / Projektauftrag Vorstudie genehmigt / Plantermin: Vorstudie Ende / Vorstudie genehmigt.
Bitte die Reihenfolge gem. Bild im ppt. umsetzen (jeweils 2 untereinander, 2 nebeneinander). Ist dies technisch nicht machbar (wäre schade), bitte folgende Reihenfolge einhalten: Plantermin: Vorstudie Start / Plantermin: Vorstudie Ende / Projektauftrag Vorstudie genehmigt / Vorstudie genehmigt.
