### ISSUE TITLE
Bauvorhaben - Register Termine VS  P1

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#287]
Prio 1 	--> muss vor Testing vorhanden sein

Bauvorhaben - Register Termine

Fehler bitte anpassen gem. ppt.
Bitte wo möglich Platz sparen (enger, kleiner, besser angeordnet). So sind die Termine zu gross/weit auseinander.

[WiKIS - Zusatzinfos zu Issues.pptx](https://github.com/user-attachments/files/16349816/WiKIS.-.Zusatzinfos.zu.Issues.pptx)

**Comment by edgar-butwilowski-win** [comment]
Die Checkbox "Vorstudie" wird nun auch in der "Übersicht" markiert, wenn sie im Bereich "Termine" markiert wurde. Das Datum "Vorstudie Ende" kann nun gesetzt werden.

**Comment by edgar-butwilowski-win** [comment]
Das grosszügige Spacing der grafischen Elemente ist im modernen UI-Design üblich. Grund dafür ist es, ein UI anzubieten, das auch von Menschen mit besonderen Ansprüchen an die Lesbarkeit und Bedienbarkeit gut verwendet werden kann.
