### ISSUE TITLE
In Tabelle auf Willkommensseite wird der Projektleiter statt der Gebietsmanager angezeigt 

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#3]
In der Tabelle auf der Willkommensseite wird aktuell wird Projektleiter statt Gebietsmanager dargestellt, obwohl die Spalte mit "Gebietsmanager" beschriftet ist. Bitte dahingehend korrigieren, dass tatsächlich der Gebietsmanager angezeigt wird.

**Comment by edgar-butwilowski-win** [comment]
Oder wäre es an dieser Stelle doch sinnvoller, den (richtigen) Projektleiter anzuzeigen statt des Gebietsmanagers?

**Comment by morasax** [comment]
Hallo Edgar. Genau, bitte GM anzeigen wie besprochen. LG Monica

**Comment by morasax** [comment]
Es werden neben dem Gebietsmanagement auch PL und andere Infos angezeigt. Bitte issue schliessen, ich lösche diesen in meinem Dokument (erledigt). Erweiterungen besprechen wir am 20.11.2023, wenn nötig erfolgt neuer Issue.
