### ISSUE TITLE
Im Vernehmlassungsprozess sollen die vorgefertigten Rundmails immer zugänglich bleiben

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#320]
Wenn aktuell ein Prozessschritt eingeleitet wird, bei dem eine vorgefertigte Mail erzeugt wird, dann ist dieser Mailentwurf nur ein mal verfügbar. Sobald die Mail geschlossen wird, kann sie nicht mehr aufgerufen werden. Es soll jedoch so sein, dass der Mailentwurf immer wieder geöffnet werden kann, solange der jeweilige Prozessschritt (bzw. Status) noch aktiv ist.

**Comment by morasax** [comment]
Mein aktueller Test hat folgendes ergeben: Ich kann bei einem Bauvorhaben die "Bedarfsklärung durchführen" wählen. Die Mail die dann erscheinen müsste, erscheint nicht. Aktiv wird dann aber der Button "Rundmail senden" (was ist das??). Drücke ich diesen, wird eine Mail generiert. Die "Bedarfsklärung durchführen" bleibt inaktiv.

**Comment by edgar-butwilowski-win** [comment]
Statt Button "Rundmail senden" gibt es nun ein Mail-Icon hinter den Buttons "Bedarfsklärung durchführen" und "Stellungnahme durchführen".
