### ISSUE TITLE
In der Karte eines Bauvorhabens das Bauvorhaben ab Status "koordiniert" mit durchgezogener Linie darstellen

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#325]
- Das Bauvorhaben soll erst mit **durchgezogener Linie** dargestellt werden, wenn das Attribut (Datum) "SKS, genehmigt" gesetzt ist und der Status des Bauvorhabens "koordiniert" lautet
- Die dem Bauvorhaben zugehörigen Bedarfe sollen dann gar nicht mehr in der Karte dargestellt werden

**Comment by morasax** [comment]
Siehe Mail zu Ticket

**Comment by edgar-butwilowski-win** [comment]
Erledigt:
- Bauvorhaben wird in der Karte "Editieren des Bauvorhabens" mit durchgezogener Linie dargestellt, wenn das Attribut (Datum) "SKS, genehmigt" gesetzt ist und der Status des Bauvorhabens "koordiniert" lautet
- Die dem Bauvorhaben zugehörigen Bedarfe werden dann gar nicht mehr in der Karte dargestellt

**Comment by morasax** [comment]
Kann ich leider nicht testen zu Ende testen.
Ich habe als Admin nun alle Termine für das 2025 gesetzt, da unter Termine -> Genehmigung Sitzung terminiert und Sitzung genehmigt entweder "Sitzung konnte nicht ermittelt werden" erschien, oder ich keinen Termin auswählen konnte. Auch nicht mit Login GM. 
Ohne Sitzungstermine SKS kann ich nicht weiterfahren - dies wäre das "SKS, genehmigt". 

Aus meiner Sicht stimmen die Farben (Violett oder Blau) sowie Linie (durchgezogen oder gestrichelt) noch nicht ganz.

- Bedarf erfasst -> Bedarf/11 -> violett gestrichelt (korrekt)
- Bauvorhaben übernommen -> in Prüfung/12 -> violett und blau gestrichelt -> Nein, müsste sein: Bauvorhaben blau gestrichelt und Bedarf violette Linie
- in Bedarfsklärung -> dito in Prüfung/12
- verifiziert -> dito in Prüfung/12
- Stellungnahme -> dito in Prüfung/12
- koordiniert -> dito in Prüfung/12 -> erst mit setzen Datum "SKS genehmigt" Wechsel zu "Blaue Linie" ohne Bedarf (kein violett). Dies ist ein zusätzlicher Schritt welcher der GM auslöst. Solange er bei SKS genehmigt kein Datum setzt, bleibt das koordinierte Bauvorhaben. Ich schicke dir per sep. Mail nochmals die pptx mit der entsprechenden Folie welche dies genau aufzeigt.

**Comment by edgar-butwilowski-win** [comment]
Im Schritt "Bauvorhaben übernommen" hat der Bedarf bereits eine durchgezogene violette Linie. Es wirkt nur so, als wäre sie gestrichelt, da initial Bauvorhaben und Bedarf genau übereinander liegen. Wenn die Geometrie des Bauvorhabens nachträglich geändert wird, dann lässt sich gut erkennen, dass der Bedarf tatsächlich durchgezogen ist.

Im Status "koordiniert" wechselt das Bauvorhaben bereits zur durchgezogenen Linie wenn das SKS-Datum gesetzt ist, hier ist aktuell allerdings noch ein Neuöffnen des Bauvorhabens notwendig, um die Änderung zu sehen. Dies habe ich nun so angepasst, dass ein Neuöffnen in Zukunft nicht mehr notwendig sein wird. Dies muss ich allerdings noch ausspielen.
