### ISSUE TITLE
Statusübergang zu "Vorstudie" soll nur von Status "koordiniert" aus möglich sein

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#329]
Statuswechsel wird eingeleitet, wenn "Vorstudie" aktiv ist und Datum "Projektauftrag Vorstudie" gesetzt wird. Aktuell wird _immer_ SSP-34 geworfen

**Comment by morasax** [comment]
Was ist SSP-34?

**Comment by edgar-butwilowski-win** [comment]
Könntest du bitte auf der Startseite des WiKIS mal CTRL+F5 drücken? Und dann bitte nochmal die Fehlermeldung «provozieren», dann sollte da nicht mehr SSP-34 stehen.

Gruss
Edgar


Von: morasax ***@***.***>
Gesendet: Montag, 2. September 2024 14:19
An: Geoinformation-Winterthur/roadwork-portal-client ***@***.***>
Cc: Butwilowski Edgar ***@***.***>; Assign ***@***.***>
Betreff: Re: [Geoinformation-Winterthur/roadwork-portal-client] Statusübergang zu "Vorstudie" soll nur von Status "koordiniert" aus möglich sein (Issue #329)


Was ist SSP-34?

**Comment by edgar-butwilowski-win** [comment]
SSP-34 ist ein interner Fehlercode. Das Front- und Backend tauschen bei Problemen diese Fehlercodes aus. Der Endbenutzer bekommt diese Codes auch ergänzend mitgeteilt. Dadurch lassen sich in einer Fehlercodeliste ergänzende Informationen zu den gemeldeten Fehlern führen.

**Comment by morasax** [comment]
Ach so, vielen Dank für die Erläuterung.

LG
Monica

Von: Edgar Butwilowski ***@***.***>
Gesendet: Montag, 2. September 2024 14:37
An: Geoinformation-Winterthur/roadwork-portal-client ***@***.***>
Cc: Ramsperger Saxer Monica ***@***.***>; Comment ***@***.***>
Betreff: Re: [Geoinformation-Winterthur/roadwork-portal-client] Statusübergang zu "Vorstudie" soll nur von Status "koordiniert" aus möglich sein (Issue #329)


SSP-34 ist ein interner Fehlercode. Das Front- und Backend tauschen bei Problemen diese Fehlercodes aus. Der Endbenutzer bekommt diese Codes auch ergänzend mitgeteilt. Dadurch lassen sich in einer Fehlercodeliste ergänzende Informationen zu den gemeldeten Fehlern führen.
