### ISSUE TITLE
Der Absender einer Rundmail soll selbst nur im CC erscheinen

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#332]

**Comment by edgar-butwilowski-win** [comment]
Es ist noch zu prüfen, ob sich dies technisch realisieren lässt.

**Comment by morasax** [comment]
Dies ist korrekt, so lange der Absender der GM ist (was eigentlich nicht anders sein dürfte, da nur der GM die Vernehmlassungs-Mails absenden darf gem. Prozess)
--> im CC soll immer der entsprechende GM eingesetzt werden
