### ISSUE TITLE
Löschen von Bauvorhaben (Prio 2)

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#334]
Bauvorhaben -> Stammdaten -> Button "Löschen" (darf nur Admin).
IST: Wird dieser Button gedrückt, wird aktuell das Bauvorhaben unter Bauvorhaben gelöscht. Nach dem Löschen erscheint dieses wieder als Bedarf unter dem Register Bedarfe. Da ich die Stati nicht mehr sehe, weiss ich nicht, welchen Status dieser Bedarf nun hat, ich gehe davon aus dass dieser nun wieder 11/Bedarf aufweist.
Es darf aber nicht sein, dass gelöschte Bauvorhaben unter den Bedarfen wieder aktiv erscheinen (als wären sie neu).

Lösung: Mit drücken des Button "Löschen" soll eine Begründung hinterlegt werden müssen (Textfeld). Darin soll kurz erläutert werden, warum das Bauvorhaben gelöscht wird (Bsp. wurde zusammengelegt mit Projekt XY). Mit Löschen soll das Bauvorhaben den Status "sistiert" erhalten.

**Comment by edgar-butwilowski-win** [comment]
- Beim Löschen eines Bauvorhabens muss ein Löschkommentar an den Bedarfen angehängt werden
- Darstellung am Bedarf ergänzen: "Schon mal bearbeitet"

**Comment by edgar-butwilowski-win** [comment]
Umsetzung erfolgt entsprechend Gespräch folgendermassen: Gebietsmanager setzt Kommentar beim Löschen eines Bauvorhabens. Bauvorhaben wird vollständig aus der Datenbank gelöscht. Der Kommentar (Löschkommentar) wird auf alle Bedarfe übertragen, die bisher an dem Bauvorhaben hingen. Jeder dieser Bedarfe hat damit eine Kopie des Löschkommentars. Die entsprechenden Bedarfe werden als "schon mal bearbeitet" angezeigt. Wenn die Bedarfe jedoch wieder einem neuen Bauvorhaben angehängt werden, wird der Löschkommentar wieder entfernt und der Bedarf wird nicht mehr als "schon mal bearbeitet angezeigt.

**Comment by morasax** [comment]
Nein, so ist die Umsetzung nicht ganz korrekt.
Definiert ist, dass nur der Admin den Button «Löschen» sieht. Diese behalten wir bei. Ergo: Nur der Admin darf löschen. Danach erhalten sie den Status «sistiert». Die entsprechende «Anleitung» ist im #334 hinterlegt (Auftragserfassung). Ich habe deinen Kommentar entsprechend angepasst, welcher nun wie folgt lautet:
Admin setzt Kommentar beim Löschen eines Bauvorhabens (wird durch drücken des Button erzwungen -> Darin soll kurz erläutert werden, warum das Bauvorhaben gelöscht wird (Bsp. wurde zusammengelegt mit Projekt XY).). Bauvorhaben wird vollständig aus der Datenbank gelöscht. Der Kommentar (Löschkommentar) wird auf alle Bedarfe übertragen, die bisher an dem Bauvorhaben hingen. Jeder dieser Bedarfe erhält damit eine Kopie des Löschkommentars. Die entsprechenden Bedarfe werden als "sistiert" angezeigt (unter Bedarfen). Wenn die Bedarfe jedoch wieder einem neuen Bauvorhaben angehängt werden, wird der Löschkommentar entfernt und der Bedarf wird nicht mehr als "sistiert» angezeigt.

Unter den «Bedarfen» muss ich (mind. als Admin) alle Stati einsehen können bzw. diese filtern können. Wir haben auch bei den Bedarfen mehrere Stati.
11/Bedarf ENTWURF (Entwurf gibt es auch bei Bauvorhaben, einfach andere Phase)
11/Bedarf
11/Bedarf archiviert (archiviert gibt es auch bei Bauvorhaben, einfach andere Phase)
11/Bedarf sistiert (sistiert gibt es auch bei Bauvorhaben, einfach andere Phase) 
-> aus einem Entwurf wird ein Bedarf, aus dem Bedarf ein «Bedarf in einem Bauvorhaben/Bauvorhaben» und aus einem Bauvorhaben gelöscht kann ein Bedarf sistiert werden, aus welchem ein archiviert werden kann, oder wieder ein «Bedarf in einem Bauvorhaben/Bauvorhaben).
Ein Teil davon wurde bereits in #22 erwähnt. -> ich habe diesbezüglich ein neues Ticket eröffnet #363
Wir hatten schon mehrfach über diese Stati geredet, aber umgesetzt wurden sie bisher nicht.

**Comment by edgar-butwilowski-win** [comment]
Falls der Gebietsmanager einen Bauvorhaben im Entwurfsstadium löscht, dann braucht es keinen Löschkommentar. Alle angehängten Bedarfe werden dann beim Löschen in den Status "Bedarf" statt "sistiert" versetzt.

**Comment by morasax** [comment]
Bitte obige Kommentare ignorieren. Es gilt Folgendes:

Löschen ist generell nur mit Drücken des Button "Löschen" möglich

**Button Löschen als GM** -> nur möglich, wenn Bauvorhaben im Entwurf. Dann wird das Bauvorhaben gelöscht und angehängte Bedarfe gehen zurück in Phase 11/Bedarf (ohne spezielle Hinweise/Vermerke).

**Button Löschen als ADMIN** -> bei Bedarfen und Bauvorhaben möglich. Nur anzuwenden, wenn effektiv etwas doppelt oder falsch erfasst wurde. Mit Drücken des Button Löschen wird das Bauvorhaben endgültig gelöscht und der darin enthaltene Bedarf herausgelöst. Der Bedarf geht zurück zu «Bedarfe» und erhält den Status «bearbeitet». Gleichzeitig wird ein Bemerkungsfeld geöffnet, welches auszufüllen ist. Erst dann kann gespeichert werden. Der Bedarf (bzw. alle daraus entkoppelten Bedarfe) erhalten den selben Status und den selben Vermerkt in der Historie. Die Bedarfe müssen anschliessend durch den GM geprüft werden, ob noch aktuell (weiterbearbeiten), oder zu archivieren.

**Comment by morasax** [comment]
Button Löschen als GM -> nur möglich, wenn Bauvorhaben im Entwurf. Dann wird das Bauvorhaben gelöscht und angehängte Bedarfe gehen zurück in Phase 11/Bedarf (ohne spezielle Hinweise/Vermerke).
**--> Test als GM hat nicht funktioniert.** Ich habe einen Bedarf als Bauvorhaben übernommen. Bauvorhaben Entwurf via Button "Löschen" nicht möglich, es passiert nichts.

Button Löschen als ADMIN -> nur bei Bauvorhaben möglich. Nur anzuwenden, wenn effektiv etwas doppelt oder falsch erfasst wurde. Mit Drücken des Button Löschen wird das Bauvorhaben endgültig gelöscht und der darin enthaltene Bedarf herausgelöst. Der Bedarf geht zurück zu «Bedarfe» und erhält den Status «bearbeitet». Gleichzeitig wird ein Bemerkungsfeld geöffnet, welches auszufüllen ist. Erst dann kann gespeichert werden. Der Bedarf (bzw. alle daraus entkoppelten Bedarfe) erhalten den selben Status und den selben Vermerkt in der Historie. Die Bedarfe müssen anschliessend durch den GM geprüft werden, ob noch aktuell (weiterbearbeiten), oder zu archivieren.
**--> Test als Admin hat nicht funktioniert.** Ich habe (den selben Bedarf wie oben) versucht als Admin zu löschen. Fehler undefined SSP-39 erscheint

**Comment by edgar-butwilowski-win** [comment]
Wie auch hier beschrieben, haben wir keinen Filter auf das Status-Attribut bei den Bedarfen: https://github.com/Geoinformation-Winterthur/roadwork-portal-client/issues/252 Daher ist der Bedarf nach dem Löschen des Bauvorhabens nicht mehr sichtbar. Solch ein Bedarf kann nach aktuellem Stand nur noch im CSV-Export eingesehen werden. Wenn das problematisch ist, dann können wir den Status-Filter bei den Bedarfen wieder einführen. Aber dann hat ein Bedarf auch im UI sichtbar den Status "Bedarf" und eben weitere Status. Aktuell ist der Status "Bedarf" beim Bedarf für den User verborgen.

**Comment by edgar-butwilowski-win** [comment]
Beim GM passe ich es bald noch an, sodass hier kein Kommentar angegeben werden muss.

**Comment by edgar-butwilowski-win** [comment]
Korrektur beim GM ist nun vorgenommen und in PROD ausgespielt. App-Version ist gleich geblieben. Der GM kann nun Bauvorhaben-Entwürfe löschen, ohne einen Kommentar angeben zu müssen. Bedarf erscheint dann wieder in Liste. Bitte um Prüfung und Rückmeldung.
