### ISSUE TITLE
Attribute Realisierungstermine bei Baubedarf zu Schiebereglern ändern

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#34]
Attribute "Früheste Realisierung", "Optimale Realisierung", "Späteste Realisierung" zu Schiebereglern ändern. Min. Termin jeweils heutiges Datum, Max. Termin + 10 Jahre. Schrittweite Quartal.

**Comment by morasax** [comment]
Schieberegler wurden umgesetzt - ich schliesse das Ticket. Es besteht ein aktuelleres Ticket zu den Schiebereglern
