### ISSUE TITLE
Usertest - GM kann Bedarf anpassen d.h. Dokumente hochladen (Prio 1)

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#345]
Unter «Bedarf» mit Login GM kann der GM Dokumente hochladen – das darf nicht sein. Nur der Bedarfssteller (und der Admin) dürfen Bedarfe verändern können, dies bezieht sich auf alle Felder in «Bedarfe»
Generell dürfen die Bedarfe nur durch den Bedarfssteller erstellt und verändert werden. Nach absenden (publizieren) darf der Bedarf nicht mehr verändert werden.

**Comment by edgar-butwilowski-win** [comment]
Dies ist nun in DEV behoben (jedoch noch nicht in PROD ausgerollt).

Aktuell darf der Admin (und nur der Admin) auch nach Publikation eines Bedarfs den Bedarf noch verändern. Ist das noch so, oder soll auch der Admin die Bedarfe nach Publikation nicht mehr editieren können?
