### ISSUE TITLE
Usertest - Dokument hinzufügen, anpassen/erweitern (Prio 2)

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#346]
- Nach dem Hochladen wird «PDF-Dokument» angezeigt – hier soll der Name des hochgeladenen Dokuments angezeigt werden.
- Es müssen mehrere Dokumente hinterlegt werden können, nicht nur eines.

**Comment by edgar-butwilowski-win** [comment]
Das braucht einen ziemlich umfangreichen Umbau. Gilt das nur für Bauvorhaben, oder auch für Bedarfe? Also sollen nur am Bauvorhaben mehrere PDF-Dokumente angehängt werden können und an Bedarfen weiterhin je nur eines, oder sollen auch an Bedarfen mehrere Dokumente angehängt werden können?

**Comment by morasax** [comment]
Ja, es muss bei Bedarfen und Bauvorhaben möglich sein, mehrere Dokumente anzuhängen.
Theoretisch gibt es bei den Bedarfen keine bis wenige Dokumente, bei den Bauvorhaben können es aber mehrere sein. Wir können das Ticket auch auseinandernehmen, so dass Bauvorhaben mit Prio bearbeitet wird, Bedarfe erst später. Was meinst du?
