### ISSUE TITLE
Vernehmlassung anpassen/umbauen (Prio 1)

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#356]
Bauvorhaben -> Stammdaten -> Übersicht -> Vernehmlassung
- Alle Informationen zu "Vernehmlassung" hier nicht mehr anzeigen (werden verschoben zu "Vernehmlassung").

Bauvorhaben -> Vernehmlassung
- Neues Sub-Tab mit Titel "Übersicht"
- Informationen aus "Stammdaten -> Übersicht -> Vernehmlassung" hierher verschieben. Von hier werden diese künftig bearbeitet. Alle Texte plus Chips verschieben 
- Wenn Bedarfsklärung oder Stellungnahme durch GM abgeschlossen wurde, hier anzeigen inkl. Datum

Bauvorhaben -> Vernehmlassung
- Sub-Tab "Infoversand" ausblenden - dieses wird erst später ggf. benötigt.

[WiKIS - Zusatzinfos zu Issues - Vernehmlassung_Übersicht.pptx](https://github.com/user-attachments/files/17811786/WiKIS.-.Zusatzinfos.zu.Issues.-.Vernehmlassung_Ubersicht.pptx)

![2024-11-19_091412](https://github.com/user-attachments/assets/f2d9524c-f964-4019-b4a6-892428cfb6fa)

**Comment by morasax** [comment]
Bitte bei der Übersicht in den Vernehmlassungen den Button "Infoverstand durchführen" entfernen.
Da wir dies aktuell in den Vernehmlassungen nicht (mehr) vorgesehen haben, soll auch der Button nicht mehr angezeigt werden.

**Comment by edgar-butwilowski-win** [comment]
Button "Infoversand durchführen" ist nun auch entfernt.
