### ISSUE TITLE
Umbau Kostenschätzung - bitte neu erstellen, Denkfehler (P1)

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#393]
#397

Die bestehende Kostenschätzung muss umgebaut werden.

- Projekt-Art-> bitte umbenennen zu **Kostenträger** 
- Arbeitsbezeichnung -> bitte umbenennen zu **Finanzierung**

Innerhalb der Finanzierung bitte Neubau/Ersatz wie folgt umbenennen:
- Neubau -> bitte umbenennen zu **ungebunden**
- Ersatz -> bitte umbenennen zu **gebunden**

Bei Finanzierung (ehemals Arbeitsbezeichnung) bitte folgende Info hinterlegen:
Neubau = mind. 1 Teil ungebundene Ausgabe, wenn Ersatz = alles gebundene Ausgaben

Bitte Kommentar für "Kanton" ändern. Text soll wie folgt lauten:
Bitte im Vernehmlassungsprozess AfM berücksichtigen

**Comment by edgar-butwilowski-win** [comment]
Kostenschätzung befindet sich am Bedarf, jedoch bei einer "Tiefbau"-Organisation

**Comment by morasax** [comment]
Es haben sich aufgrund der neuen Formulare in Provis und Abacus Änderungen ergeben:
Die bestehende Kostenschätzung muss nochmals angepasst werden - Anpassung von 3 Texten.

- Kostenträger-> bitte umbenennen zu **Kostenstelle**

Bitte wieder umbenennen. Innerhalb der Finanzierung bitte Neubau/Ersatz wie folgt umbenennen:
- Neubau -> bitte umbenennen zu **Neu**
- Ersatz -> bitte umbenennen zu **Unterhalt**

**Comment by morasax** [comment]
Lieber Edgar

Ich musste nochmals eine Anpassung aufgrund der neuen Formulare vornehmen. Bitte entschuldige.

LG
Monica

Von: Edgar Butwilowski ***@***.***>
Gesendet: Freitag, 15. November 2024 17:12
An: Geoinformation-Winterthur/roadwork-portal-client ***@***.***>
Cc: Ramsperger Saxer Monica ***@***.***>; Author ***@***.***>
Betreff: Re: [Geoinformation-Winterthur/roadwork-portal-client] Umbau Kostenschätzung - bitte neu erstellen, Denkfehler (P1) (Issue #393)


Closed #393<https://github.com/Geoinformation-Winterthur/roadwork-portal-client/issues/393> as completed via #396<https://github.com/Geoinformation-Winterthur/roadwork-portal-client/pull/396>.

**Comment by edgar-butwilowski-win** [comment]
Ist nun entsprechend angepasst
