### ISSUE TITLE
Filter zurückstellen bei Baubedürfnissen P3

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#4]
Sobald Bezeichnung eingetragen ist, kann sie scheinbar nicht mehr rausgenommen werden.

**Comment by edgar-butwilowski-win** [comment]
Kann ich nicht nachvollziehen, ich habe es eben ausprobiert. Sobald ich die Rückschritttaste (Backspace) drücke, ist der Filter zurückgestellt und es werden wieder alle Baubedürfnisse angezeigt. Evtl. nochmal gemeinsam anschauen.

**Comment by morasax** [comment]
Hier die Rückmeldung von Tobias:
Das ist nur ein kleines etwas störendes Detail. Ich gehe davon aus, dass die bessere Filter- und Listenfunktion das wieder weniger wichtig macht, erläutere aber gerne meinen Gedankengang:
Mit Backspace kann man tatsächlich die «Bezeichnung» wieder löschen. Da ich aber ohne Verwendung der Tastatur aktuell ein Baubedürnis auswählen kann, dachte ich, ich sollte so auch wieder im Dropdown-Menü zu anderen oder allen Baubedürfnissen kommen. Bei den Baumassnahmen ist es so umgesetzt, dass ich mit der Maus von allen zu einer komme und dort auswählen kann. Mit einem «alle» oder einfach einem leeren Feld im Dropdown könnte dies ebenfalls erreicht werden.
LG Monica

**Comment by morasax** [comment]
Prio 3	 --> erfolgt nach GoLive. Wird gesammelt und periodisch in die aktive Umgebung aufgenommen.

**Comment by morasax** [comment]
Wird gem. Test an heutigem Meeting geschlossen
