### ISSUE TITLE
Vernehmlassung Eingabemaske/Formular und Prozessschritte Stellungnahme (Prio 1)

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#400]
Bitte das Formular für die Stellungnahme anpassen (bestehend, muss umgebaut werden)

- Baubeginn und Bauende einfügen (aus Sub-Register Zeitliche Koordination -> TBD)

- Kein Bedarf mehr 
- Weiterhin Bedarf vorhanden
   - Ja, das Bauvorhaben inkl. des geschätzten Realisierungszeitraums passt
   - Nein, ich bin nicht einverstanden, bitte um Kontaktaufnahme

- Rückmeldung
- Senden

Logik ist im pptx beschrieben.

[WiKIS - Zusatzinfos zu Issues - Vernehmlassung_Eingabeformular_Stellungnahme.pptx](https://github.com/user-attachments/files/17812058/WiKIS.-.Zusatzinfos.zu.Issues.-.Vernehmlassung_Eingabeformular_Stellungnahme.pptx)

![2024-11-19_093425](https://github.com/user-attachments/assets/238657d6-d4d3-479a-a054-fa5079fe1717)

**Comment by edgar-butwilowski-win** [comment]
Braucht es hier überhaupt noch ein Textfeld für die Rückmeldung? Wird die Rückmeldung nicht bereits durch die Single-Choice-Auswahl vollständig gegeben?

**Comment by morasax** [comment]
Nein, ist es nicht. Ja, es braucht ein Rückmeldungs-Feld. Es ist freiwillig und ob jemand effektiv eine zusätzliche Rückmeldung hat, kann ich aktuell nicht sagen. Es ist aber wichtig, dass die Möglichkeit besteht, sollte noch zusätzlich eine Info von Nöten sein.

LG
Monica

Von: Edgar Butwilowski ***@***.***>
Gesendet: Montag, 9. Dezember 2024 17:42
An: Geoinformation-Winterthur/roadwork-portal-client ***@***.***>
Cc: Ramsperger Saxer Monica ***@***.***>; Author ***@***.***>
Betreff: Re: [Geoinformation-Winterthur/roadwork-portal-client] Vernehmlassung Eingabemaske/Formular und Prozessschritte Stellungnahme (Prio 1) (Issue #400)


Braucht es hier überhaupt noch ein Textfeld für die Rückmeldung? Wird die Rückmeldung nicht bereits durch die Single-Choice-Auswahl vollständig gegeben?

**Comment by edgar-butwilowski-win** [comment]
Das Textfeld für Rückmeldung ist in V 2024.32 wieder reaktiviert.
