### ISSUE TITLE
Sub Tab Übersicht bei Bauvorhaben anpassen (vor Go Live)

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#405]
Anpassen des bestehenden Sub-Tab Übersicht (bei Bauvorhaben unter Stammdaten)
Nachfolgende sind bereits vorhanden und sollen so bleiben (müssen jedoch teils bearbeitbar sein) -> siehe grüne Kästchen:
- UUID (Universelle ID) -> Direkte Anzeige der automatisch generierten Nummer
- Strabako-Nr. -> bearbeitbar durch GM
- Projekt-Nr. -> bearbeitbar durch GM, Vorschlag durch System
 - Titel/Strasse -> bearbeitbar durch GM
 - Abschnitt ->bearbeitbar durch GM
 - *Auslösegrund -> bearbeitbar durch GM
 - Bemerkung -> bearbeitbar durch GM
 - Auslösendes Werk / Auslöser, usw. -> alles so belassen, nur Anzeige

Nachfolgende müssen neu erstellt und/oder verschoben werden:
- "Voraussichtliche Termine" umbenennen zu "Nächst mögliche Sitzungstermine"->und verschieben unterhalb der Phase/Status
- Alle Button oben rechts platzieren, oberhalb von "Auslösendes Werk". Dies sind Speichern/Löschen/sistieren/archivieren
- Phase 5, Realisierung -> Baubeginn/-ende kleiner bzw. kompakter darstellen, andere Daten weglassen
- Titel neu hinzufügen: "Vorhaben enthält Aspekte" (wenn ja, dann Titel anzeigen, und alle im Register "Eigenschaften" angewählten Häklein - wenn nein d.h. keine gesetzten Häklein, Information ganz weglassen
- Lead Realisierung mit Auswahlfeld für Werk/Oe sowie PL (nach Projekttyp)
- Darstellung der SIA-Phasen gem. aktuellen Terminplan (siehe #412) 
- Dokumente - alles zu Up-/Download verschieben nach "Dokumente"

![1](https://github.com/user-attachments/assets/50821151-03c2-4156-ad6d-b54fe337ffdf)

![2](https://github.com/user-attachments/assets/ec02ba0f-1230-45c6-9501-c2b73aee2698)

[WiKIS - Zusatzinfos zu Issues - Sub-Tab Bauvorhaben.pptx](https://github.com/user-attachments/files/18082041/WiKIS.-.Zusatzinfos.zu.Issues.-.Sub-Tab.Bauvorhaben.pptx)

**Comment by edgar-butwilowski-win** [comment]
Alles erledigt, bis auf "Vorhaben enthält Aspekte", "Lead Realisierung" und "Darstellung der SIA-Phasen". Diese habe ich in separate Issues extrahiert: #437, #438 und #439.  Bevor ich diese umsetzen kann, braucht es noch Rücksprache (nächste Besprechung).
