### ISSUE TITLE
Anzeige Register beim Erfassen von Bauvorhaben anpassen (vor Go Live)

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#406]
Auftrag: Anpassen der Register Anzeige (Bauvorhaben erfassen)
Beim Erfassen eines Bauvorhaben sollen zu Beginn nur folgende Tabs ersichtlich sein:
- Perimeter
- Übersicht
- Bedarfe
-> alle anderen Tabs sollen erst nach Speichern ersichtlich werden
Vorgehen: Perimeter erfassen -> Stammdaten erfassen -> Bedarf(e) zuweisen -> speichern

**Comment by edgar-butwilowski-win** [comment]
Das Register "Bedarfe" kann erst nach dem ersten Speichern des Baubedarfs angezeigt werden, da die Berechnung des räumlichen Verschnitts zwischen Bedarfen und dem Bauvorhaben datenbankseitig durchgeführt wird (das entlastet das Front-End). Dazu muss jedoch das Bauvorhaben bereits erstmalig gespeichert sein, um datenbankseitig vorzuliegen.
