### ISSUE TITLE
Auf der Willkommensseite soll der "Lead" angezeigt werden

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#43]
"Lead" ist die Organisation des Bedarfsstellers.

**Comment by morasax** [comment]
Den Lead zeigen wir unter Bauvorhaben auf der Übersicht an. Zudem ist unter Willkommen nur das ersichtlich, was einem in irgend einer Form etwas angeht. Ticket wird geschlossen da mittlerweile die Anzeige der Willkommensseite in einem anderen Ticket erfasst wurde. Falls nötig, wird diese Anfrage zu einem späteren Zeitpunkt mit neuem Ticket eröffnet
