### ISSUE TITLE
Kosten - bitte Text bei "Kanton" anpassen (nach GoLive)

### ISSUE THREAD

**Issue by morasax** [Geoinformation-Winterthur/roadwork-portal-client#433]
Aktuell wird bei der Hinterlegung der Kosten der Text "Kanton muss einbezogen werden" angezeigt.
Bitte den Text und ein Wort ergänzen auf: "Kanton (AfM) muss einbezogen werden.

**Comment by edgar-butwilowski-win** [comment]
Aktuell (in Version 2024.32 lautet der Text genau "Bitte im Vernehmlassungsprozess AfM berücksichtigen". Ich passe dies nun an zu: "Kanton (AfM) muss einbezogen werden"

**Comment by morasax** [comment]
Zum Zeitpunkt der Ticketerfassung konnte nicht nachvollzogen werden, welcher Text effektiv hinterlegt war/ist. Ich sah die Version 2024.32 noch nicht.
Der bestehende Text wäre gut gewesen. Der neue ist aber auch ok.

Von: Edgar Butwilowski ***@***.***>
Gesendet: Montag, 30. Dezember 2024 16:22
An: Geoinformation-Winterthur/roadwork-portal-client ***@***.***>
Cc: Ramsperger Saxer Monica ***@***.***>; Author ***@***.***>
Betreff: Re: [Geoinformation-Winterthur/roadwork-portal-client] Kosten - bitte Text bei "Kanton" anpassen (nach GoLive) (Issue #433)


Aktuell (in Version 2024.32 lautet der Text genau "Bitte im Vernehmlassungsprozess AfM berücksichtigen". Ich passe dies nun an zu: "Kanton (AfM) muss einbezogen werden"
