### ISSUE TITLE
Öffnen eines Baubedürfnisses per Klick auf den Titel P1

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#6]
Beim Klick auf den Namen/Titel einer Baubedürfnis-Karte sollte diese öffnen. Der separate Button "Öffnen" ist dann überflüssig und kann entfernt werden.

**Comment by edgar-butwilowski-win** [comment]
Ich weiss nicht, ob es Vorteile bringt, das zu ändern. In der Übersicht der Baubedürfnisse verwenden wir aktuell als UI-Element die sog. "Cards" aus dem Material Design. Material Design ist eine Designsprache mit Fokus auf Usability. Die Standard-Cards sehen vor, dass alle Aktionen (wie "Öffnen", "Löschen") in einem separaten "Actions"-Bereich unten an der Karte angebracht werden. Solche Cards kommen mittlerweile auch in anderen Applikationen vor und haben dort häufig das Standard-Verhalten, wodurch eine Intuition bei der Bedienung entsteht. Wenn wir davon abweichen, geht evtl. diese Intuition bei der Bedienung hier verloren.

**Comment by edgar-butwilowski-win** [comment]
Siehe: https://material.angular.io/components/card/examples

**Comment by morasax** [comment]
Lieber Edgar
Hier hätte ich ohnehin eine ganz andere Darstellung. Ich hätte dies gerne tabellarisch (Bedürfnissteller, Bauname, Link, usw.) oder direkt eine Map als Übersicht mit Darstellung aller vorhandenen Bedarfe. Erst mit Klick auf den gewünschten Bedarf öffnet sich ein Detailfenster (siehe Auszug Dokument, Pt. 6.4.1 Baubedarf). Diesen Punkt müssen wir nochmals besprechen.
LG Monica

**Comment by morasax** [comment]
Ist umgesetzt
