### ISSUE TITLE
Links "im Stadtplan"/"im WinWebGIS" im neuen Webbrowser-Tab

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#7]
Die Links "im Stadtplan"/"im WinWebGIS" auf den Baubedürfnis- und Baumassnahmen-Karten sollten in einem neuen Webbrowser-Tab statt im selben Tab aufgehen.

**Comment by edgar-butwilowski-win** [comment]
Dies ist technisch möglich. Aus Usability-Sicht wird jedoch grundsätzlich nicht mehr dazu empfohlen, das Öffnen von Tabs durch die Applikation steuern zu lassen. Hierüber soll der Benutzer selbst die volle Kontrolle behalten. Der Benutzer kann jederzeit einen Link in einem neuen Tab öffnen, z.B. unter Windows durch das Drücken des Mausrads. Sollen dies trotzdem so umgesetzt werden?

**Comment by edgar-butwilowski-win** [comment]
Als Ergänzung hierzu ein Artikel aus dem Search Engine Journal, der die Problematik im Zusammenhang mit dem automatischen Öffnen von Links in einem neuen Browser-Tab erläutert (sogar Sicherheitsrisiken): https://www.searchenginejournal.com/blank-link-attribute/435883/

**Comment by morasax** [comment]
Es handelt sich hierbei ja um den "Absprung" zum Stadplan bzw. WinWebGIS. Das Problem liegt darin, dass der Nutzer a) nach dem Öffnen ggf. nicht mehr zur Übersicht zurückkommt und b) ggf. mehrere Bedarfe und/oder Massnahmen parallel geöffnet haben möchte. Wir wären dankbar um Umsetzung in einem neuen Fenster. Falls sich dies als "falsch" herausstellen sollte, können wir zu einem späteren Zeitpunkt zurück auf die Standardversion.

**Comment by edgar-butwilowski-win** [comment]
Lösung ist in V2023.11.13 eingebaut.
