### ISSUE TITLE
Bei den Filtern der Baubedarfs- und Bauvorhaben-Übersicht soll es eine zusätzliche Option geben, mit der alle Filter auf einmal an- und abgewählt werden können P2

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#78]

**Comment by morasax** [comment]
Korrekt - bitte so beibehalten. 
Zusätzlich müssen wir definieren, welche Status/Phasen in Bedarf bzw. Bauvorhaben sichtbar sind und anwählbar sein müssen pro Rolle. Es fehlen aktuell noch div. Phasen und Stati

**Comment by morasax** [comment]
Prio 2	 --> muss mit GoLive vorhanden sein

**Comment by edgar-butwilowski-win** [comment]
Wie in der heutigen Sitzung besprochen, wird dies nun so angepasst, dass beim Status-Filter alle Auswahlmöglichkeiten mit einem Klick ab/angewählt werden können
