### ISSUE TITLE
Bei neuer Baumassnahme das Datum "Realisierung" standardmässig auf heute

### ISSUE THREAD

**Issue by edgar-butwilowski-win** [Geoinformation-Winterthur/roadwork-portal-client#8]
Beim Neuerfassen der Baumassnahme das Datum "Realisierung" standardmässig auf heute setzen

**Comment by edgar-butwilowski-win** [comment]
Das Datum "Realisierung" ist bereits auf das jeweils tagesaktuelle Datum voreingestellt.

**Comment by morasax** [comment]
Ich weiss nicht, woher der Issue kam (keine Notiz in meinem Dokument). Gem. meinem Test funktioniert es (Realisierungsdatum = heute). Bitte abschliessen.
